project:
  type: website
  output-dir: docs

website:
  title: "Megan's Mind"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
    tools:
      - icon: github
        menu: 
          - text: GitHub Profile
            href: https://github.com/meganjane333
  sidebar:
    style: "docked"
    background: light
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

