project:
  type: website

website:
  title: "pers_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        menu: 
          - text: Profile
            href: https://github.com/meganjane333

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

